SkillsFundingAgency/das-shared-packages

Messaging/PubSubSampleGui/Program.cs
Messaging/PubSubSampleGui/Properties/AssemblyInfo.cs
Messaging/PublishReceiveSample/Program.cs
Messaging/SFA.DAS.Messaging.AzureServiceBus/AzureServiceBusMessageService.cs
Messaging/SFA.DAS.Messaging.AzureServiceBus/SFA.DAS.Messaging.AzureServiceBus.nuspec
Messaging/SFA.DAS.Messaging.AzureStorageQueue/AzureStorageQueueService.cs
Messaging/SFA.DAS.Messaging.AzureStorageQueue/Properties/AssemblyInfo.cs
Messaging/SFA.DAS.Messaging.AzureStorageQueue/SFA.DAS.Messaging.AzureStorageQueue.nuspec
Messaging/SFA.DAS.Messaging.Syndication.SqlServer/SFA.DAS.Messaging.Syndication.SqlServer.nuspec
Messaging/SFA.DAS.Messaging.Syndication.SqlServer/SqlServerMessageRepository.cs
Messaging/SFA.DAS.Messaging.Syndication.UnitTests/HalTests/JsonTests/HalJsonMessageClientTests/WhenGettingBatchOfUnseenMessages.cs
Messaging/SFA.DAS.Messaging.Syndication.UnitTests/HalTests/JsonTests/HalJsonMessageClientTests/WhenGettingNextUnseenMessage.cs
Messaging/SFA.DAS.Messaging.Syndication.UnitTests/HalTests/JsonTests/HalJsonMessageServiceTests/WhenGettingAPage.cs
Messaging/SFA.DAS.Messaging.Syndication.UnitTests/SFA.DAS.Messaging.Syndication.UnitTests.csproj
Messaging/SFA.DAS.Messaging.Syndication.UnitTests/SyndicationMessageTests/WhenAborting.cs
Messaging/SFA.DAS.Messaging.Syndication.UnitTests/SyndicationPollingMessageReceiverTests/WhenReceivingBatchAsAsync.cs
Messaging/SFA.DAS.Messaging.Syndication/Hal/Json/HalJsonMessageClient.cs
Messaging/SFA.DAS.Messaging.Syndication/Hal/Json/HalJsonMessageService.cs
Messaging/SFA.DAS.Messaging.Syndication/Hal/Json/IHalJsonMessageService.cs
Messaging/SFA.DAS.Messaging.Syndication/IMessageClient.cs
Messaging/SFA.DAS.Messaging.Syndication/IMessageRepository.cs
Messaging/SFA.DAS.Messaging.Syndication/SFA.DAS.Messaging.Syndication.csproj
Messaging/SFA.DAS.Messaging.Syndication/SFA.DAS.Messaging.Syndication.nuspec
Messaging/SFA.DAS.Messaging.Syndication/SyndicationPage.cs
Messaging/SFA.DAS.Messaging.Syndication/SyndicationPollingMessageReceiver.cs
Messaging/SFA.DAS.Messaging/FileSystem/FileSystemMessageService.cs
Messaging/SFA.DAS.Messaging/IPollingMessageReceiver.cs
Messaging/SFA.DAS.Messaging/SFA.DAS.Messaging.nuspec
Messaging/SyndicationHost/Controllers/HalFeedController.cs
Messaging/SyndicationHost/Hal/PageLinkBuilder.cs

**This represents a breaking change to the messaging interfaces**
* Changed syndication to present and read pages in chronologic order, so that a page is a consistent resource
* Change syndication to have page size set on the repository, to support implementations where pages are materialised in the data store
* Add batch receiving to polling receiver interface

Messaging v3

---

Logging/SFA.DAS.NLog.Targets.AzureEventHub/README.MD
Logging/SFA.DAS.NLog.Targets.Redis/README.MD
Logging/SFA.DAS.NLog.Targets.Redis/RedisConnectionManager.cs
Logging/SFA.DAS.NLog.Targets.Redis/RedisTarget.cs
Logging/SFA.DAS.NLog.Targets.Redis/SFA.DAS.NLog.Targets.Redis.csproj
README.md

Required settings now
- AppName
- ConnectionStringKey
- DbSettingsKey
- KeySettingsKey

[logging redis] -> moved settings to appSettings file

---

SFA.DAS.Events.Api/SFA.DAS.Events.Api.Client/SFA.DAS.Events.Api.nuspec
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Types/AgreementStatus.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Types/ApprenticeshipEvent.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Types/ApprenticeshipEventView.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Types/PaymentStatus.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Types/SFA.DAS.Events.Api.Types.csproj
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Types/SFA.DAS.Events.Api.nuspec

-AgreementStatus
-PaymentStatus

Added enums inst of string for..

---

SFA.DAS.Events.Api/SFA.DAS.Events.Api.Client/EventsApi.Accounts.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Client/IEventsApi.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Client/SFA.DAS.Events.Api.Client.csproj
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Client/SFA.DAS.Events.Api.nuspec
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Types/AccountEvent.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Types/AccountEventView.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Types/SFA.DAS.Events.Api.Types.csproj
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Types/SFA.DAS.Events.Api.nuspec

Added types and API client required for the new accounts event stream.

Account events

---

Messaging/SFA.DAS.Messaging/EventingMessageReceiverPollingWrapper.cs
Messaging/SFA.DAS.Messaging/IEventingMessageReceiver.cs

Add RunAsync method to EventingMessageReceiver to allow it to be awaitable

Make eventing receiver awaitable

---

SFA.DAS.Events.Api/SFA.DAS.Events.Api.Client.UnitTests/EventsApiAccountTests/WhenCreateAnAccountEvent.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Client.UnitTests/EventsApiAccountTests/WhenIGetAccountEventsByDateRange.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Client.UnitTests/EventsApiAccountTests/WhenIGetAccountEventsById.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Client/SFA.DAS.Events.Api.nuspec
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Types/AccountEvent.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Types/AccountEventView.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Types/AgreementEventView.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Types/ApprenticeshipEventView.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Types/IEventView.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Api.sln
SFA.DAS.Events.Api/SFA.DAS.Events.Dispatcher.UnitTests/EventDispatcherTests/ExpectedTestEvent.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Dispatcher.UnitTests/EventDispatcherTests/OtherTestEvent.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Dispatcher.UnitTests/EventDispatcherTests/WhenIDispatchAnEvent.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Dispatcher.UnitTests/Properties/AssemblyInfo.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Dispatcher.UnitTests/SFA.DAS.Events.Dispatcher.UnitTests.csproj
SFA.DAS.Events.Api/SFA.DAS.Events.Dispatcher.UnitTests/packages.config
SFA.DAS.Events.Api/SFA.DAS.Events.Dispatcher/EventDispatcher.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Dispatcher/EventRegistration.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Dispatcher/HandlerNotRegisteredException.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Dispatcher/IEventDispatcher.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Dispatcher/IEventHandler.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Dispatcher/Properties/AssemblyInfo.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Dispatcher/SFA.DAS.Events.Dispatcher.csproj
SFA.DAS.Events.Api/SFA.DAS.Events.Dispatcher/SFA.DAS.Events.Dispatcher.nuspec

Updated events to the new format used when pubishing account events.  Also introduced a generic event dispatcher to route events to a specified handler based on their type and event name.

Account events v2

---

Logging/SFA.DAS.NLog.Logger/NLogLogger.cs

why you seal logger

---

Logging/SFA.DAS.NLog.Logger/NLogLogger.cs

checking for a null logger type before using it to get version

---

SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Client/EmployerCommitmentApi.cs
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Client/HttpCommitmentHelper.cs
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Client/Interfaces/IEmployerCommitmentApi.cs
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Client/SFA.DAS.Commitments.Api.Client.csproj
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Client/SFA.DAS.Commitments.Api.nuspec
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Types/Apprenticeship/ApprenticeshipSubmission.cs
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Types/SFA.DAS.Commitments.Api.nuspec

Added Date of Change
Removed the need for the commitment id in url

Update the Apprenticeship Patch for Employer

---

SFA.DAS.Events.Api/SFA.DAS.Events.Api.Client/EventsApi.Generic.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Client/GenericEventMapper.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Client/IEventsApi.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Client/SFA.DAS.Events.Api.Client.csproj
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Types/GenericEvent{T}.cs
SFA.DAS.Events.Api/SFA.DAS.Events.Api.Types/SFA.DAS.Events.Api.Types.csproj

adding methods to the client to allow for strongly typed message payloads

#112 Adding strongly typed events to the generic event client

---

Logging/SFA.DAS.NLog.Targets.Redis/RedisTarget.cs

adding the exception types so they appear in kibana

---

SFA.DAS.Sql/SFA.DAS.Sql.Client/BaseRepository.cs
SFA.DAS.Sql/SFA.DAS.Sql.Client/Properties/AssemblyInfo.cs
SFA.DAS.Sql/SFA.DAS.Sql.Client/SFA.DAS.Sql.Client.csproj
SFA.DAS.Sql/SFA.DAS.Sql.Client/SFA.DAS.Sql.Client.nuspec
SFA.DAS.Sql/SFA.DAS.Sql.Client/packages.config
SFA.DAS.Sql/SFA.DAS.Sql.sln

Nuget package solution for BaseRepository for SQL. Can then be applied across our solutions.

Add solution for SQL Client package

---

SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Client/SFA.DAS.Commitments.Api.nuspec
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Types/Apprenticeship/ApprenticeshipSearchQuery.cs
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Types/Apprenticeship/ApprenticeshipSearchResponse.cs
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Types/SFA.DAS.Commitments.Api.nuspec

Added some properties for DCM-629 for pagination.

Add Pagination values to search

---

SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Client/ApprenticeshipApi.cs
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Client/DataLockApi.cs
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Client/EmployerCommitmentApi.cs
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Client/HttpClientBase.cs
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Client/Interfaces/IApprenticeshipApi.cs
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Client/Interfaces/IDataLockApi.cs
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Client/Interfaces/IEmployerCommitmentApi.cs
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Client/Interfaces/IProviderCommitmentsApi.cs
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Client/ProviderCommitmentsApi.cs
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Client/SFA.DAS.Commitments.Api.nuspec
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Types/SFA.DAS.Commitments.Api.nuspec

Need to update VSTS variable. 
Waiting for access. 
https://skillsfundingagency.atlassian.net/browse/DCM-723

moved methods to provider / employer API[C

---

Messaging/SFA.DAS.Messaging/FileSystem/FileSystemMessageService.cs

- Should be saved in the created directory not the storage directory which could be missing the queue name

Fixed a bug with where the queue message was being saved

---

Messaging/PublishReceiveSample/App.config
Messaging/SFA.DAS.Messaging.AzureStorageQueue/SFA.DAS.Messaging.AzureStorageQueue.csproj
Messaging/SFA.DAS.Messaging.AzureStorageQueue/SFA.DAS.Messaging.AzureStorageQueue.nuspec
Messaging/SFA.DAS.Messaging.AzureStorageQueue/app.config
Messaging/SFA.DAS.Messaging.AzureStorageQueue/packages.config
Messaging/SFA.DAS.Messaging.Syndication.SqlServer/SFA.DAS.Messaging.Syndication.SqlServer.csproj
Messaging/SFA.DAS.Messaging.Syndication.SqlServer/SFA.DAS.Messaging.Syndication.SqlServer.nuspec
Messaging/SFA.DAS.Messaging.Syndication.SqlServer/packages.config
Messaging/SFA.DAS.Messaging.Syndication.UnitTests/SFA.DAS.Messaging.Syndication.UnitTests.csproj
Messaging/SFA.DAS.Messaging.Syndication.UnitTests/packages.config
Messaging/SFA.DAS.Messaging.Syndication/SFA.DAS.Messaging.Syndication.csproj
Messaging/SFA.DAS.Messaging.Syndication/SFA.DAS.Messaging.Syndication.nuspec
Messaging/SFA.DAS.Messaging.Syndication/packages.config
Messaging/SFA.DAS.Messaging/SFA.DAS.Messaging.csproj
Messaging/SFA.DAS.Messaging/SFA.DAS.Messaging.nuspec
Messaging/SFA.DAS.Messaging/packages.config
Messaging/SyndicationHost/SyndicationHost.csproj
Messaging/SyndicationHost/Web.config
Messaging/SyndicationHost/packages.config

Updated nuspec files to match package dependency version

Update Newtonsoft to latest stable

---

Messaging/SFA.DAS.Messaging/FileSystem/FileSystemMessageService.cs

Added the reading of the queue name from the queue name attribute to
the FileSystemMessageService

AML-1324 - Add the attribute queue name to FileSystemMessage

---

SFA.DAS.Learners/SFA.DAS.Learners.UnitTests/SFA.DAS.Learners.UnitTests.csproj
SFA.DAS.Learners/SFA.DAS.Learners.UnitTests/ValidatorTests/WhenIValidateTheUniqueLearnerNumber.cs
SFA.DAS.Learners/SFA.DAS.Learners/SFA.DAS.Learners.csproj
SFA.DAS.Learners/SFA.DAS.Learners/Validators/IUlnValidator.cs
SFA.DAS.Learners/SFA.DAS.Learners/Validators/UlnValidationResult.cs
SFA.DAS.Learners/SFA.DAS.Learners/Validators/UlnValidator.cs

Code changes to uln validation routine

Changes to validate uln number as a string input  and unit test

---

SFA.DAS.HashingService/SFA.DAS.HashingService.UnitTest/HashingServiceTest/WhenHashingIds.cs
SFA.DAS.HashingService/SFA.DAS.HashingService.UnitTest/SFA.DAS.HashingService.UnitTests.csproj
SFA.DAS.HashingService/SFA.DAS.HashingService/HashingService.cs
SFA.DAS.HashingService/SFA.DAS.HashingService/IHashingService.cs

Extended the Hashing service to handle Guid Ids

AML-1714-Consolidate_HashingService_into_single_package 

---

SFA.DAS.Sql/SFA.DAS.Sql.Dapper.Tests/AutoMoqData.cs
SFA.DAS.Sql/SFA.DAS.Sql.Dapper.Tests/ParentChildrenMapperTests/WhenMapping.cs
SFA.DAS.Sql/SFA.DAS.Sql.Dapper.Tests/Properties/AssemblyInfo.cs
SFA.DAS.Sql/SFA.DAS.Sql.Dapper.Tests/SFA.DAS.Sql.Dapper.Tests.csproj
SFA.DAS.Sql/SFA.DAS.Sql.Dapper.Tests/app.config
SFA.DAS.Sql/SFA.DAS.Sql.Dapper.Tests/packages.config
SFA.DAS.Sql/SFA.DAS.Sql.Dapper/ParentChildrenMapper.cs
SFA.DAS.Sql/SFA.DAS.Sql.Dapper/Properties/AssemblyInfo.cs
SFA.DAS.Sql/SFA.DAS.Sql.Dapper/SFA.DAS.Sql.Dapper.csproj
SFA.DAS.Sql/SFA.DAS.Sql.Dapper/SFA.DAS.Sql.Dapper.nuspec
SFA.DAS.Sql/SFA.DAS.Sql.sln

Created new package SFA.DAS.Sql.Dapper
Pulled ParentChildrenMapper and related tests from das-commitments
Converted the tests to use Automoq

Moving ParentChildMapper functionality to a shared package

---

Logging/README.md
Logging/SFA.DAS.NLog.Logger/Constants.cs
Logging/SFA.DAS.NLog.Logger/NLogLogger.cs
Logging/SFA.DAS.NLog.Logger/NlogCorrelationId.cs
Logging/SFA.DAS.NLog.Logger/SFA.DAS.NLog.Logger.csproj

Want to set correlation id for out index jobs so that its easier to follow in the logs.

Added method to set correlation id for console applications

---

Messaging/PublishReceiveSample/Program.cs
Messaging/PublishReceiveSample/PublishReceiveSample.csproj
Messaging/PublishReceiveSample/SampleLogger.cs
Messaging/PublishReceiveSample/packages.config
Messaging/SFA.DAS.Messaging.AzureServiceBus.StructureMap/SFA.DAS.Messaging.AzureServiceBus.StructureMap.csproj
Messaging/SFA.DAS.Messaging.AzureServiceBus.StructureMap/TopicMessagePublisherPolicy.cs
Messaging/SFA.DAS.Messaging.AzureServiceBus.StructureMap/app.config
Messaging/SFA.DAS.Messaging.AzureServiceBus.StructureMap/packages.config
Messaging/SFA.DAS.Messaging.AzureServiceBus/SFA.DAS.Messaging.AzureServiceBus.csproj
Messaging/SFA.DAS.Messaging.AzureServiceBus/TopicMessagePublisher.cs
Messaging/SFA.DAS.Messaging.AzureServiceBus/TopicSubscriberFactory.cs
Messaging/SFA.DAS.Messaging.AzureServiceBus/packages.config
Messaging/SFA.DAS.Messaging.Syndication.SqlServer/SFA.DAS.Messaging.Syndication.SqlServer.csproj
Messaging/SFA.DAS.Messaging.Syndication.SqlServer/app.config
Messaging/SFA.DAS.Messaging.Syndication.UnitTests/SFA.DAS.Messaging.Syndication.UnitTests.csproj
Messaging/SFA.DAS.Messaging.Syndication.UnitTests/app.config
Messaging/SFA.DAS.Messaging.Syndication/SFA.DAS.Messaging.Syndication.csproj
Messaging/SFA.DAS.Messaging.Syndication/app.config
Messaging/SFA.DAS.Messaging.Tests/SFA.DAS.Messaging.UnitTests.csproj
Messaging/SFA.DAS.Messaging.Tests/packages.config
Messaging/SFA.DAS.Messaging/MessageProcessor.cs
Messaging/SFA.DAS.Messaging/SFA.DAS.Messaging.csproj
Messaging/SFA.DAS.Messaging/app.config
Messaging/SFA.DAS.Messaging/packages.config
Messaging/Tools/PhantomJS/tools/phantomjs/ChangeLog

Added logging for the topics messaging. Need to review as we now have to work out how to inject the logger into the message policy for MA before it is defined in the IOC as policies are added before the defaultRegistry which currently have the logger defined in it

Added logging to the topic message handling code

---

SFA.DAS.Support.Shared/Readme.MD
SFA.DAS.Support.Shared/SFA.DAS.Support.Shared.sln

Created a basic readme that referes to this package

Corrected readme

---

SFA.DAS.Support.Shared/SFA.DAS.Support.Shared/IClientValidatior.cs
SFA.DAS.Support.Shared/SFA.DAS.Support.Shared/SFA.DAS.Support.Shared.csproj

Interface abstracts and allows testing of the client (token) validation mechanism

Created interface for client validation

---

README.md

Added note for NLog logging pacakge upgrade breaking change

Update Shared package Readme

---

SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.UnitTests/ApplicationSubmitTests.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.UnitTests/SFA.DAS.Recruit.Vacancies.Client.UnitTests.csproj
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/Client.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/Entities/Application.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/Entities/ApplicationQualification.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/Entities/ApplicationTrainingCourse.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/Entities/ApplicationWorkExperience.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/IClient.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/Messages/ApplicationSubmitMessage.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.csproj
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/packages.config

Added `SubmitApplication` method to the client.
This adds a message to the `application-submitted-queue` to be processed by a v2 Job

ER-573 vacancy applications

---

SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.UnitTests/ClientTests/GetVacancyTests.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.UnitTests/SFA.DAS.Recruit.Vacancies.Client.UnitTests.csproj
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.UnitTests/packages.config
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/Client.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/Entities/Vacancy.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/IClient.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.csproj

- Renamed LiveVacancy to Vacancy as this method can return closed vacancy as well

ER-652 GetVacancy to query Live and Closed both types

---

SFA.DAS.NServiceBus/SFA.DAS.NServiceBus/SFA.DAS.NServiceBus.csproj

As per @elliotritchie 's comments on other PR; remove refs rather than update.

drop redundant package refs.

---

SFA.DAS.Testing/SFA.DAS.Testing.EntityFramework/SFA.DAS.Testing.EntityFramework.csproj
SFA.DAS.Testing/SFA.DAS.Testing.UnitTests/FluentTestTests.cs
SFA.DAS.Testing/SFA.DAS.Testing.UnitTests/SFA.DAS.Testing.UnitTests.csproj
SFA.DAS.Testing/SFA.DAS.Testing.sln
SFA.DAS.Testing/SFA.DAS.Testing/FluentTest.cs
SFA.DAS.Testing/SFA.DAS.Testing/SFA.DAS.Testing.csproj

This should replace RunAsync<TException> as it gives more control over which assertions are testable

Added RunAsyncCheckException assertion

---

Messaging/SFA.DAS.Messaging/MessageProcessor2.cs

AML-3045 Fix background logger

---

Configuration/SFA.DAS.Configuration.AzureTableStorage/AzureTableStorageConfigurationRepository.cs
Configuration/SFA.DAS.Configuration/ConfigurationService.cs

Updated two await calls to remove continuation on sync context as this causes deadlock when sync context is blocking on a call that winds up in the config service

AML-1903 Add configureAwait to avoid blocking on sync context

---

.gitignore
VacancyServices.Wage/SFA.DAS.VacancyServices.Wage.UnitTests/SFA.DAS.VacancyServices.Wage.UnitTests.csproj
VacancyServices.Wage/SFA.DAS.VacancyServices.Wage.UnitTests/WagePresenterTests.cs
VacancyServices.Wage/SFA.DAS.VacancyServices.Wage.sln
VacancyServices.Wage/SFA.DAS.VacancyServices.Wage/NationalMinimumWageRates.cs
VacancyServices.Wage/SFA.DAS.VacancyServices.Wage/NationalMinimumWageService.cs
VacancyServices.Wage/SFA.DAS.VacancyServices.Wage/SFA.DAS.VacancyServices.Wage.csproj
VacancyServices.Wage/SFA.DAS.VacancyServices.Wage/SFA.DAS.VacancyServices.Wage.xml
VacancyServices.Wage/SFA.DAS.VacancyServices.Wage/WageCalculator.cs
VacancyServices.Wage/SFA.DAS.VacancyServices.Wage/WageConstants.cs
VacancyServices.Wage/SFA.DAS.VacancyServices.Wage/WageDetails.cs
VacancyServices.Wage/SFA.DAS.VacancyServices.Wage/WagePresenter.cs
VacancyServices.Wage/SFA.DAS.VacancyServices.Wage/WageType.cs
VacancyServices.Wage/SFA.DAS.VacancyServices.Wage/WageUnit.cs
VacancyServices.Wage/SFA.DAS.VacancyServices.Wage/WageUnitExtensions.cs

A package have a common location for National Minimum Wage data plus helper methods to display/ calculate wage information.

RA 2100 SFA.DAS.VacanyServices.Wage package

---

SFA.DAS.Http/SFA.DAS.Http.UnitTests/RestHttpClientTests.cs
SFA.DAS.Http/SFA.DAS.Http/IRestHttpClient.cs
SFA.DAS.Http/SFA.DAS.Http/RestHttpClient.cs

CV-70-AddPost

---

SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search.UnitTests/ApprenticeshipSearchClientTests.cs
SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search.UnitTests/TraineeshipSearchClientTests.cs
SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search/ApprenticeshipSearchClient.cs
SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search/Entities/ApprenticeshipSearchResult.cs
SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search/Entities/TraineeshipSearchResult.cs
SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search/Requests/ApprenticeshipSearchRequestParameters.cs
SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search/Requests/TraineeshipSearchRequestParameters.cs
SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search/TraineeshipSearchClient.cs

Allowing searching and sorting by the training provider's UKPRN

ER-1008 - Searching by ProviderUkprn

---

SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.UnitTests/ApplicationSubmitTests.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.UnitTests/SFA.DAS.Recruit.Vacancies.Client.UnitTests.csproj
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.UnitTests/app.config
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.csproj
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/app.config
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/packages.config
SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search.UnitTests/SFA.DAS.VacancyServices.Search.UnitTests.csproj
SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search.UnitTests/app.config
SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search.csproj

Updating the .net framework to v4.6.2 for Vacancies.Client and VacancyServices.Search

ER-1254_upgrade sharedpackages

---

.gitignore
SFA.DAS.EmployerUrlHelper/README.md
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper.Sample/Controllers/HomeController.cs
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper.Sample/Program.cs
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper.Sample/Properties/launchSettings.json
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper.Sample/SFA.DAS.EmployerUrlHelper.Sample.csproj
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper.Sample/Startup/AspNetStartup.cs
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper.Sample/Startup/ConfigurationStartup.cs
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper.Sample/Views/Home/Index.cshtml
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper.Sample/Views/Shared/_Layout.cshtml
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper.Sample/Views/_ViewImports.cshtml
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper.Sample/Views/_ViewStart.cshtml
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper.Sample/appsettings.Development.json
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper.Sample/appsettings.json
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper.sln
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper/EmployerUrlConfiguration.cs
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper/ILinkGenerator.cs
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper/LinkGenerator.cs
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper.csproj
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper/ServiceCollectionExtensions.cs

Configuration: https://github.com/SkillsFundingAgency/das-employer-config/pull/321

CV-285 Added employer url helper

---

SFA.DAS.EmployerUrlHelper/.vscode/tasks.json
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper.UnitTests/LinkGeneratorTests.cs
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper/Configuration/EmployerUrlHelperConfiguration.cs
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper/LinkGenerator.cs

Added the finance url to config here: https://github.com/SkillsFundingAgency/das-employer-config/pull/356

Add Finance Url

---

SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper.UnitTests/LinkGeneratorTests.cs
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper/DependencyResolution/ServiceCollectionExtensions.cs
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper/ILinkGenerator.cs
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper/Mvc/UrlHelperExtensions.cs
SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper/SFA.DAS.EmployerUrlHelper.csproj

- Allows passing in of IConfiguration
- Removed netcoreapp as a target framework
- Added missing method on ILinkGenerator 😨 (my bad)

Add setup overload

---

SFA.DAS.Employer.Shared.UI/IntegrationTests/Tests/MenuTests.cs
SFA.DAS.Employer.Shared.UI/IntegrationTests/sharedMenuSettings.json
SFA.DAS.Employer.Shared.UI/README.md
SFA.DAS.Employer.Shared.UI/SFA.DAS.Employer.Shared.UI/Configuration/MaPageConfiguration.cs
SFA.DAS.Employer.Shared.UI/SFA.DAS.Employer.Shared.UI/SFA.DAS.Employer.Shared.UI.csproj
SFA.DAS.Employer.Shared.UI/SFA.DAS.Employer.Shared.UI/ServiceCollectionExtensions.cs
SFA.DAS.Employer.Shared.UI/SFA.DAS.Employer.Shared.UI/Views/Shared/_Menu.cshtml

FC-707 Update Menu Component

---

SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Attributes/SuppressNavigationSectionAttribute.cs
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Extensions/ViewDataExtensions.cs
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/NavigationSection.cs
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Startup/Extensions.cs
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/ViewDataKeys.cs
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Views/Shared/_Menu.cshtml

Adds feature to suppress nav sections

Adds Reservations nav section

---

SFA.DAS.NServiceBus/SFA.DAS.NServiceBus.AzureFunction/Infrastructure/NServiceBusListener.cs

The error queue name is now taken from the endpoint name with _error
appended to it.

MF-257 - Change error queue name for AzureFunction NSB

---

SFA.DAS.Hmrc/azure-pipelines.yml

Add YAML file to build Nuget package for SFA.DAS.Hmrc.

Adding build pipeline

---

SFA.DAS.NServiceBus/SFA.DAS.NServiceBus.AzureFunction/Hosting/NServiceBusListener.cs
SFA.DAS.NServiceBus/SFA.DAS.NServiceBus/Configuration/AzureServiceBus/EndpointConfigurationExtensions.cs
SFA.DAS.NServiceBus/SFA.DAS.NServiceBus/SFA.DAS.NServiceBus.csproj

This change will allow us to use Managed Service Identities to access the Azure Service Bus, no more need for credentials in connection strings

NServiceBus MSI Authentication

---

SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search.UnitTests/IntegrationTests/LocationSearchClientIntegrationTests.cs
SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search.UnitTests/SFA.DAS.VacancyServices.Search.UnitTests.csproj
SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search.UnitTests/app.config

Adds integration test after the upgrade to Elasticsearch 7.5 to ensure we can retrieve content from the Locations index once its built

Qual 251 adds integration test

---

SFA.DAS.MA.Shared.UI/azure-pipelines.yml

Setup azure-pipeline build yml for SFA.DAS.MA.Shared.UI

Setup azure-pipeline build yml for SFA.DAS.MA.Shared.UI

---

SFA.DAS.MA.Shared.UI/azure-pipelines.yml

Change to windows agent as net462

Change to windows agent as net462

---

SFA.DAS.NServiceBus/SFA.DAS.NServiceBus.SqlServer/SFA.DAS.NServiceBus.SqlServer.csproj
SFA.DAS.NServiceBus/SFA.DAS.NServiceBus.Testing/SFA.DAS.NServiceBus.Testing.csproj
SFA.DAS.NServiceBus/SFA.DAS.NServiceBus/SFA.DAS.NServiceBus.csproj
SFA.DAS.Testing/SFA.DAS.Testing.EntityFramework/SFA.DAS.Testing.EntityFramework.csproj
SFA.DAS.Testing/SFA.DAS.Testing/SFA.DAS.Testing.csproj
SFA.DAS.UnitOfWork/SFA.DAS.UnitOfWork.EntityFramework/SFA.DAS.UnitOfWork.EntityFramework.csproj
SFA.DAS.UnitOfWork/SFA.DAS.UnitOfWork.EntityFrameworkCore/SFA.DAS.UnitOfWork.EntityFrameworkCore.csproj
SFA.DAS.UnitOfWork/SFA.DAS.UnitOfWork.Mvc/SFA.DAS.UnitOfWork.Mvc.csproj
SFA.DAS.UnitOfWork/SFA.DAS.UnitOfWork.NServiceBus/SFA.DAS.UnitOfWork.NServiceBus.csproj
SFA.DAS.UnitOfWork/SFA.DAS.UnitOfWork.SqlServer/SFA.DAS.UnitOfWork.SqlServer.csproj
SFA.DAS.UnitOfWork/SFA.DAS.UnitOfWork.WebApi/SFA.DAS.UnitOfWork.WebApi.csproj
SFA.DAS.UnitOfWork/SFA.DAS.UnitOfWork/SFA.DAS.UnitOfWork.csproj
SFA.DAS.Vacancy.Analytics.Client/SFA.DAS.Vacancy.Analytics.Client/SFA.DAS.Vacancy.Analytics.Client.csproj
SFA.DAS.Validation/SFA.DAS.Validation.Mvc/SFA.DAS.Validation.Mvc.csproj
SFA.DAS.Validation/SFA.DAS.Validation.WebApi/SFA.DAS.Validation.WebApi.csproj
SFA.DAS.Validation/SFA.DAS.Validation/SFA.DAS.Validation.csproj
VacancyServices.Wage/SFA.DAS.VacancyServices.Wage/SFA.DAS.VacancyServices.Wage.csproj

Packages updated and confirmed various agent pool changes for the following build pipelines
- SFA.DAS.NServiceBus
- SFA.DAS.Testing
- SFA.DAS.UnitOfWork
- SFA.DAS.Vacancy.Analytics.Client
- SFA.DAS.VacancyServices.Wage
- SFA.DAS.Validation

Dasd 8045 change agent pool

---

SFA.DAS.HashingService/SFA.DAS.HashingService.Console/Program.cs
SFA.DAS.HashingService/SFA.DAS.HashingService.Console/SFA.DAS.HashingService.Console.csproj
SFA.DAS.HashingService/SFA.DAS.HashingService.UnitTest/HashingServiceTest/WhenHashingIds.cs
SFA.DAS.HashingService/SFA.DAS.HashingService.sln

EI-351 Create a console app for encoding/decoding Ids to aid production support

---

SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Attributes/HideNavigationBarAttribute.cs
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Extensions/ViewDataExtensions.cs
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/ViewDataKeys.cs
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Views/Shared/_Menu.cshtml

CON-3029 Provider shared navigation bar hide navigation bar options

---

SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/Entities/Vacancy.cs

Added account id and account legal entity hashed ids to the Vacancy entity

FAI-67 - Add hashed account ids

---

SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI.UnitTests/Extensions/HttpHelperZendeskExtensionsTests.cs

Fai 101 csp setting on scripts

---

SFA.DAS.GovUK.Auth/SFA.DAS.GovUK.Auth.UnitTests/Services/OidcService/WhenPopulatingAccountClaims.cs
SFA.DAS.GovUK.Auth/SFA.DAS.GovUK.Auth/Services/OidcService.cs
SFA.DAS.GovUK.Auth/SFA.DAS.GovUK.SampleSite/Views/Home/Authenticated.cshtml
SFA.DAS.OidcMiddleware/SFA.DAS.Oidc.Middleware.TestSite/Global.asax.cs
SFA.DAS.OidcMiddleware/SFA.DAS.OidcMiddleware.GovUk.UnitTests/Services/WhenPopulatingAccountClaims.cs
SFA.DAS.OidcMiddleware/SFA.DAS.OidcMiddleware.GovUk/Services/OidcService.cs

Update claim type names used and ensure sub is mapped correctly

FAI-630 update claims returned

---

SFA.DAS.Employer.Shared.UI/SFA.DAS.Employer.Shared.UI/SFA.DAS.Employer.Shared.UI.csproj

for compatibility with .net core 3.1

MAC-150 Allow multi targeting with netstandard 

---

SFA.DAS.GovUK.Auth/SFA.DAS.GovUK.Auth.UnitTests/Extensions/WhenGettingSignedOutUrl.cs
SFA.DAS.GovUK.Auth/SFA.DAS.GovUK.Auth/AppStart/AddAndConfigureGovUkAuthenticationExtension.cs
SFA.DAS.GovUK.Auth/SFA.DAS.GovUK.Auth/AppStart/ConfigureGovUkAuthenticationExtension.cs
SFA.DAS.GovUK.Auth/SFA.DAS.GovUK.Auth/AppStart/ConfigureGovUkStubAuthenticationExtension.cs
SFA.DAS.GovUK.Auth/SFA.DAS.GovUK.Auth/Extensions/SignedOutRedirectExtension.cs
SFA.DAS.GovUk.Auth.Samples/SFA.DAS.GovUK.SampleSite/appsettings.json

Add signout url creation for gov sign in

FAI-729 employer signed out

---

SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Attributes/SetDfESignStatusValuesAttribute.cs
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Extensions/ViewDataExtensions.cs
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Startup/Extensions.cs
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Views/Shared/_ProviderMenu.cshtml

Commit Details: Included Change Sign in details link in the navigation menu
Story: https://skillsfundingagency.atlassian.net/browse/FAI-735

FAI-735 Included Change Sign in details link in the navigation menu

---

VacancyServices.Wage/SFA.DAS.VacancyServices.Wage.UnitTests/NationalMinimumWageServiceTests.cs
VacancyServices.Wage/SFA.DAS.VacancyServices.Wage/NationalMinimumWageService.cs
VacancyServices.Wage/SFA.DAS.VacancyServices.Wage/SFA.DAS.VacancyServices.Wage.csproj

Added a new nationalMinimumWageRate record for 2023, and added 2 unit tests

Changed min wage for 2023

---

SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Views/Shared/_ProviderMenu.cshtml

Changes from Testing Team
Settings menu should not be visible when UseDfESignIn toggle is set false

Fai 735 change provider settings menu toggle

---

SFA.DAS.DfESignIn.Auth.Samples/SFA.DAS.DfESignIn.SampleSite/AppStart/AddServiceRegistrationExtension.cs
SFA.DAS.DfESignIn.Auth.Samples/SFA.DAS.DfESignIn.SampleSite/Controllers/HomeController.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/AddAndConfigureDfESignInAuthenticationExtension.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/ConfigureDfESignInAuthenticationExtension.cs

Commit Details
Add re-direct url to the DfESignIn Nuget Pkg
Story: https://skillsfundingagency.atlassian.net/browse/FAI-886

FAI-886 Log off Users from DfE SignIn

---

SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/ConfigureSharedAuthenticationExtension.cs

Change same site mode to none for auth cookie so the cookie can be shared between sub domains

FAI-1063 - Change cookie same site mode to none

---

Configuration/azure-pipelines.yml
pipeline-templates/job/code-build.yml

Updated Sonarcloud to v2 for code build and updates das-platform-building-blocks version for batch 1

Updated Sonarcloud to v2 for code build and updates das-platform-building-blocks version for batch 1

---

SFA.DAS.Employer.Shared.UI/IntegrationTests/IntegrationTests.csproj
SFA.DAS.Employer.Shared.UI/IntegrationTests/Tests/TestBase.cs
SFA.DAS.Employer.Shared.UI/IntegrationTests/Tests/UrlBuilderTests.cs
SFA.DAS.Employer.Shared.UI/SFA.DAS.Employer.Shared.UI.UnitTests/SFA.DAS.Employer.Shared.UI.UnitTests.csproj
SFA.DAS.Employer.Shared.UI/SFA.DAS.Employer.Shared.UI/Configuration/MaRoutes.cs
SFA.DAS.Employer.Shared.UI/SFA.DAS.Employer.Shared.UI/SFA.DAS.Employer.Shared.UI.csproj
SFA.DAS.Employer.Shared.UI/azure-pipelines.yml
SFA.DAS.Employer.Shared.UI/example-website/example-website.csproj

- Added new TrainingRequest route to the UrlBuilder for Recruit (employer)
- Upgraded SFA.DAS.Employer.Shared.UI to .Net 8
- Updated packages

FAI-2665 Add new training request route to the url builder
