SkillsFundingAgency/das-shared-packages

Logging/SFA.DAS.NLog.Targets.AzureEventHub/AzureEventHubTarget.cs
Logging/SFA.DAS.NLog.Targets.AzureEventHub/SFA.DAS.NLog.Targets.AzureEventHub.csproj
Logging/SFA.DAS.NLog.Targets.AzureEventHub/SFA.DAS.NLog.Targets.AzureEventHub.nuspec
Logging/SFA.DAS.NLog.Targets.AzureEventHub/packages.config
README.md

Made a change so that the configuration settings for the EventHub logging are read from app setting keys instead of from the config directly. I haven't removed the old parameters but have taken off the RequiredParameter attribute and marked as obsolete in the code

Logging connection string change

---

SFA.DAS.OidcMiddleware/SFA.DAS.Oidc.Middleware.TestSite/Startup.cs
SFA.DAS.OidcMiddleware/SFA.DAS.OidcMiddleware/OidcMiddlewareOptions.cs
SFA.DAS.OidcMiddleware/SFA.DAS.OidcMiddleware/SFA.DAS.OidcMiddleware.csproj
SFA.DAS.OidcMiddleware/SFA.DAS.OidcMiddleware/SFA.DAS.OidcMiddleware.nuspec
SFA.DAS.OidcMiddleware/SFA.DAS.OidcMiddleware/Strategies/AuthenticateCoreStrategy.cs
SFA.DAS.OidcMiddleware/SFA.DAS.OidcMiddleware/TokenValidationMethod.cs
SFA.DAS.OidcMiddleware/SFA.DAS.OidcMiddleware/Validators/SecurityTokenValidation.cs

Make token validation method configurable to support signing certificate. This is to support IDS implementation.
Also makes breaking change as built in name => ClaimTypes.Name translation has been removed as it is specific to an IDP provider. This can be done in AuthenticatedCallback if needed by client

Oidc middleware updates for ids

---

SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Client/CommitmentsApi.cs
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Client/ICommitmentsApi.cs
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Types/Commitment.cs
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Types/CommitmentListItem.cs
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Types/CommitmentSubmission.cs
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Types/LastUpdateInfo.cs
SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.Types/SFA.DAS.Commitments.Api.Types.csproj

Takes the name and email of the submitter when Patching Commitment
Adds Employer and Provider properties onto Commitment with the last
updater.

Update Commitment Patch for Employer and Provider

---

SFA.DAS.Events.Api/SFA.DAS.Events.Api.Client/Configuration/IEventsApiClientConfiguration.cs

When I create a concrete class for IEventsApiClientConfiguration I can't use an expression-bodied property because it requires setters.

removing setters from events API configuration interface

---

Logging/SFA.DAS.NLog.Logger/NLogLogger.cs

This now takes the version from the passed type instead of using the version on the logger nuget package

Log the application version instead of logger version

---

Logging/SFA.DAS.NLog.Logger/NLogLogger.cs
Logging/SFA.DAS.NLog.Targets.Redis/RedisTarget.cs

In one of our worker roles we use host multiple indexers and we pragmatically set the application name. So in order to adopt this package I've added a way to override the app_Name in the redis target.

Override the app_Name on the redis target

---

Logging/SFA.DAS.NLog.Targets.Redis/SFA.DAS.NLog.Targets.Redis.nuspec

it was missing and it's required by the redis package

adding Microsoft.WindowsAzure.ConfigurationManager to the nuspec file

---

Logging/SFA.DAS.NLog.Logger/NLogLogger.cs

A couple changes to fix #82
- adds a dictionary to the constructor of the NLogLogger to allow for properties like the version to be overridden
- removes the default version number being the NLogLogger assembly version

allow properties in the constructor of the Logger

---

Messaging/PublishReceiveSample/PublishReceiveSample.csproj
Messaging/SFA.DAS.Messaging.AzureServiceBus/AzureServiceBusMessageService.cs
Messaging/SFA.DAS.Messaging/FileSystem/FileSystemMessageService.cs

This change allows you to send different messages to different queues using the same connection set in the Publisher.
If the queuename is set it will fall back to that

Aml 1239 multiple message type support

---

Messaging/SFA.DAS.Messaging.AzureServiceBus/TopicMessageSubscriber.cs

- We have tried to catch de-serialisation exceptions when converting the brokered message to a typed one but the exceptions seem to still get thrown as fatal later on. Given we know that this code does only one thing at the moment we have created a catch all to dead letter messages that fail to be converted as this can this be sorted later on. This code is a quick fix and will be handled better later on.

Catching all exception when de-serializing and dead lettering message

---

SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute.UnitTests/ApiSubstituteTests.cs
SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute.UnitTests/Properties/AssemblyInfo.cs
SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute.UnitTests/SFA.DAS.ApiSubstitute.UnitTests.csproj
SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute.UnitTests/TestAccount.cs
SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute.UnitTests/WebApiSubstituteTests.cs
SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute.UnitTests/packages.config
SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute.WebAPI/App.config
SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute.WebAPI/MessageHandlers/ApiMessageHandlers.cs
SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute.WebAPI/MessageHandlers/DelegateHandler.cs
SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute.WebAPI/OwinSelfHost/WebApiStartUp.cs
SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute.WebAPI/Properties/AssemblyInfo.cs
SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute.WebAPI/SFA.DAS.ApiSubstitute.WebAPI.csproj
SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute.WebAPI/SFA.DAS.ApiSubstitute.WebAPI.nuspec
SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute.WebAPI/WebApiSubstitute.cs
SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute.WebAPI/packages.config
SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute.sln

Substitute any Api response by setting the Gets in the Http message handlers.

Api Substitute using HttpMessagehandlers

---

SFA.DAS.OidcMiddleware/SFA.DAS.OidcMiddleware/CodeFlowAuthenticationHandler.cs

Replace the throw exception in CodeFlowAuthenticationHandler.AuthenticateCoreAsync with just returning null. There seems to be some disagreement over whether it should return null or an access token with null properties - the documentation is not clear so took steer from https://brockallen.com/2013/08/07/owin-authentication-middleware-architecture/

Replace throw exception with just null authentication ticket

---

SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute.UnitTests/SFA.DAS.ApiSubstitute.UnitTests.csproj
SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute/SFA.DAS.ApiSubstitute.UnitTests/packages.config

- We have had issues with the build server not liking the standard version of the Task extensions nuget that latest version of Moq depends on. Given the tests don't need the latest version i've downgraded the version to see if that solves the issue in the short term.

Downgrade moq as we have had build issue with latest release

---

SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.UnitTests/Properties/AssemblyInfo.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.UnitTests/SFA.DAS.Recruit.Vacancies.Client.UnitTests.csproj
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.UnitTests/VacancyVersionHelperTests.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.UnitTests/packages.config
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.sln
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/Client.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/Entities/Address.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/Entities/LiveVacancy.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/Entities/Qualification.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/Entities/TrainingProvider.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/Entities/Wage.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/IClient.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/Properties/AssemblyInfo.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.csproj
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.nuspec
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/VacancyVersionHelper.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/packages.config

.NET version is the same as FAA (4.5.1)
Mongo driver is the same as that used by FAA (1.10.0)
`Client.cs` has a single public function `GetVacancy`. This returns a vacancy as it is in the query store.
`VacancyVersionHelper.cs` is a helper class to determine what version a vacancy is by its number. 10 digits means it is a v2 vacancy.

ER-378 - Recruit Vacancy Client

---

SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.nuspec

Build process doesn't seem to use nuget pack option and therefore dependencies are not automatically included

RA-1949 Added dependencies to nuspec file

---

SFA.DAS.Testing/SFA.DAS.Testing.EntityFramework/DbSetStub.cs

Add entity operations to DbSetStub.
EAS (on AML-2818-EnsureEventsForProviderRelationships branch) has been updated to use latest (this version) SFA.DAS.Testing.EntityFramework (with no regressions).
Changes required for and tested on SFA.DAS.ProviderRelationships' AML-2818-add-message-handlers branch.

Enhance Entity Framework Stub

---

SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.UnitTests/ApplicationWithdrawTests.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.UnitTests/SFA.DAS.Recruit.Vacancies.Client.UnitTests.csproj
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/Client.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/IClient.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/Messages/ApplicationWithdrawMessage.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.csproj

Added `WithdrawApplication` method to client which adds a message to the new `application-withdrawn-queue` queue.
Note - v2 is not aware of FAA's application Id. So we target applications by CandidateId/VacancyReference combo.

ER-727 - Withdraw Application

---

Messaging/SFA.DAS.Messaging.Tests/ObjectExtensionTests.cs
Messaging/SFA.DAS.Messaging.Tests/SFA.DAS.Messaging.UnitTests.csproj
Messaging/SFA.DAS.Messaging/MessageProcessor.cs
Messaging/SFA.DAS.Messaging/ObjectExtensions.cs
Messaging/SFA.DAS.Messaging/SFA.DAS.Messaging.csproj

Log non-null message contents received by message processors to allow better diagnostics when investigating message problems.

AML-2894 Log message contents

---

Messaging/SFA.DAS.Messaging.Tests/MessageProcessor2Tests.cs
Messaging/SFA.DAS.Messaging.Tests/SFA.DAS.Messaging.UnitTests.csproj
Messaging/SFA.DAS.Messaging/Interfaces/IMessageProcessor2.cs
Messaging/SFA.DAS.Messaging/MessageProcessor.cs
Messaging/SFA.DAS.Messaging/MessageProcessor2.cs
Messaging/SFA.DAS.Messaging/SFA.DAS.Messaging.csproj

This provides an alternative to the existing MessageProcessor (imaginatively named MessageProcessor2) which doesn't accept a cancellation token source and does not seek to stop all other message handlers hanging on the same cancellation token source.

Add MessageProcessor2 to accept CancellationToken

---

SFA.DAS.Http/SFA.DAS.Http/SFA.DAS.Http.csproj

Downgrading newtonsoft json to version 9.0.1 from version 10.x as the consumer library in FAA cannot be upgraded to version 10.x.

RA-2088 downgrades newtonsoft json

---

SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search.UnitTests/ApprenticeshipSearchClientTests.cs
SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search.UnitTests/TraineeshipSearchClientTests.cs
SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search/ApprenticeshipSearchClient.cs
SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search/Extensions/SearchDescriptorExtensions.cs
SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search/Requests/ApprenticeshipSearchRequestParameters.cs
SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search/Requests/TraineeshipSearchRequestParameters.cs
SFA.DAS.VacancyServices.Search/SFA.DAS.VacancyServices.Search/TraineeshipSearchClient.cs

In FAA if you select 'England' as the radius then no SearchRadius is specified so we do not filter by lat/long.   This meant the 'distance' being returned in the results was 0.
The lat/long is passed into the search though so we can still Sort by GeoDistance even if we can't Filter on it.  So this ticket allows us to do this and return the distance in the search results.

ER-2080 GeoDistance sort without radius

---

SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/Entities/Vacancy.cs

There is behaviour in FAA that needs to know whether the vacancy is anonymous or not.
There are a couple of ways we can do this. I can infer that the vacancy is anonymous by looking at the address of the projected vacancy and if address line 1-4 are empty and the postcode is an outcode then I can assume the vacancy is anonymons.....This feels hacky so I think explicitly adding a new 'anonymous' field to the projection is the correct thing to do.
Initially I was contemplating exposing `EmployerNameOption` in the vacancy projection. But this enum  feels like an internal thing that doesn't make much sense outside of the v2 applications.
So I think just adding a bool `IsAnonymous` to the projection and its set by `EmployerNameOption == Anonymous`.
What do you think?

ER-1020 - Added IsAnonymous

---

Configuration/SFA.DAS.Configuration.AzureTableStorage/AzureTableStorageConfigurationProvider.cs
Configuration/SFA.DAS.Configuration.AzureTableStorage/AzureTableStorageConfigurationSource.cs
Configuration/SFA.DAS.Configuration.AzureTableStorage/ConfigurationBootstrapper.cs
Configuration/SFA.DAS.Configuration.AzureTableStorage/ConfigurationBuilderExtensions.cs
Configuration/SFA.DAS.Configuration.AzureTableStorage/ConfigurationOptions.cs
Configuration/SFA.DAS.Configuration.AzureTableStorage/EnvironmentVariables.cs
Configuration/SFA.DAS.Configuration.AzureTableStorage/StorageOptions.cs
Configuration/SFA.DAS.Configuration.UnitTests/AzureTableStorage/AzureTableStorageConfigurationProviderTests.cs
Configuration/SFA.DAS.Configuration.UnitTests/AzureTableStorage/ConfigurationBootstrapperTests.cs

To give the option of configuration keys not being prefixed with the RowKey Name a flag can now be passed.
This allows the json configuration structure to remain the same whether using appSetting.json, secrets.json or Azure Table Storage.
The down side is that if you do you multiple azure configurations then a collision of names is possible.

Add flag to prevent prefixing of configuration variables

---

Configuration/SFA.DAS.Configuration.AzureTableStorage/AzureTableStorageConfigurationProvider.cs

Unlike the other providers the Azure table storage configuration provider wasn't making it's dictionary case insensitive. Which meant when looking for property names from the object it was binding to it wouldn't match. 🐐

Make data dictionary case insensitive

---

SFA.DAS.Testing/SFA.DAS.Testing.AzureStorageEmulator/AzureStorageEmulatorManager.cs

I just realised it needs to gracefully handle the process not being able to start.  Chances are the build server and AT won't have the emulator installed!

Don't exception if the process can't start.

---

Configuration/SFA.DAS.Configuration.AzureTableStorage/AzureTableStorageConfigurationProvider.cs
Configuration/SFA.DAS.Configuration.AzureTableStorage/AzureTableStorageConfigurationSource.cs
Configuration/SFA.DAS.Configuration.AzureTableStorage/ConfigurationBootstrapper.cs
Configuration/SFA.DAS.Configuration.AzureTableStorage/ConfigurationBuilderExtensions.cs
Configuration/SFA.DAS.Configuration.AzureTableStorage/ConfigurationOptions.cs
Configuration/SFA.DAS.Configuration.AzureTableStorage/StorageOptions.cs
Configuration/SFA.DAS.Configuration.TestHarness/Program.cs
Configuration/SFA.DAS.Configuration.TestHarness/SFA.DAS.Configuration.TestHarness.csproj
Configuration/SFA.DAS.Configuration.UnitTests/AzureTableStorage/AzureTableStorageConfigurationProviderTests.cs
Configuration/SFA.DAS.Configuration.UnitTests/AzureTableStorage/ConfigurationBootstrapperTests.cs
Configuration/SFA.DAS.Configuration.UnitTests/AzureTableStorage/ConfigurationBuilderExtensionsTests.cs
Configuration/SFA.DAS.Configuration.UnitTests/TestHelpers.cs
Configuration/SFA.DAS.Configuration.sln

Add option to directly pass StorageConnectionString & EnvironmentName.
Also, throw useful message if config row not present & populate options with defaults before calling back to consumer.

Configuration: Add option to directly pass StorageConnectionString & EnvironmentName

---

SFA.DAS.NServiceBus/SFA.DAS.NServiceBus/AzureServiceBus/EndpointConfigurationExtensions.cs
SFA.DAS.NServiceBus/SFA.DAS.NServiceBus/SFA.DAS.NServiceBus.csproj

Revert "Removed .NET Framework specific Azure Service Bus configuration" to prevent legacy .NET Framework consumers having to upgrade their Microsoft.IdentityModel.Clients.ActiveDirectory package right now
This reverts commit fc9720c0ac32d2b5e12f1bef92446c9ea0d5a775.

Revert "Removed .NET Framework specific Azure Service Bus configuration"

---

SFA.DAS.NServiceBus/SFA.DAS.NServiceBus.AzureFunction.UnitTests/SFA.DAS.NServiceBus.AzureFunction.UnitTests.csproj
SFA.DAS.NServiceBus/SFA.DAS.NServiceBus.AzureFunction/Hosting/NServiceBusListener.cs
SFA.DAS.NServiceBus/SFA.DAS.NServiceBus.AzureFunction/SFA.DAS.NServiceBus.AzureFunction.csproj
SFA.DAS.NServiceBus/SFA.DAS.NServiceBus.SqlServer.UnitTests/SFA.DAS.NServiceBus.SqlServer.UnitTests.csproj
SFA.DAS.NServiceBus/SFA.DAS.NServiceBus.UnitTests/SFA.DAS.NServiceBus.UnitTests.csproj

I've found issues with using the same version of the SFA.DAS.NServiceBus nuget with the SFA.DAS.NServiceBus.AzureFunction nuget. The problem was that the azure function nuget referenced a nuget version of the NServiceBus package which was different to the version it one even though it was in the same solution. It makes sense to keep these two nugets in sync version wise so have now changed it to a project reference. Adding reviewers that i think may be interested in this change

Now uses project references rather than nugets to aid in version matching

---

SFA.DAS.Http/SFA.DAS.Http/Configuration/IJwtClientConfiguration.cs
SFA.DAS.Http/SFA.DAS.Http/Configuration/IStaticJwtClientConfiguration.cs
SFA.DAS.Http/SFA.DAS.Http/SFA.DAS.Http.csproj
SFA.DAS.Http/SFA.DAS.Http/TokenGenerators/JwtBearerTokenGenerator.cs
SFA.DAS.Http/SFA.DAS.Http/TokenGenerators/StaticJwtBearerTokenGenerator.cs

This PR replaces the existing `JwtTokenGenerator` class with one that actually generates JWT tokens.
The original implementation has been renamed to `StaticJwtGenerator`
Example implementation:
```
class Program
{
public class JwtClientConfiguration : IJwtClientConfiguration
{
public string Issuer {get; set;}
public string Audience {get; set;}
public string ClientSecret {get; set;}
public int TokenExpirySeconds {get; set;}
}
static void Main(string[] args)
{
var config = new JwtClientConfiguration
{
Issuer = "xxx",
Audience = "xxx",
ClientSecret = "xxx",
TokenExpirySeconds = 500,
};
var gen = new JwtBearerTokenGenerator(config);
var tok = gen.Generate();
Console.WriteLine(tok.Result);
}
}
```

Implement real token generation

---

SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client.UnitTests/ClientTests/GetVacancyTests.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/Client.cs
SFA.DAS.Recruit.Vacancies.Client/SFA.DAS.Recruit.Vacancies.Client/IClient.cs

FAA was querying all the live vacancies without any batching process. Now that the live vacancies are adding up, we need to allow FAA to batch process it. Added two methods to allow batching, one to get live vacancy count and other to retrieve live vacancy in batches.

QUAL-408 enable paging in live vacancies

---

SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI.Tests/Extensions/WhenConstructingTheExternalUrl.cs
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI.Tests/SFA.DAS.Provider.Shared.UI.Tests.csproj
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Extensions/ExternalUrlHelper.cs
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Models/ProviderSharedUIConfiguration.cs
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Models/UrlParameters.cs
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI.csproj
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Startup/AddServiceExtensions.cs
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Startup/Extensions.cs
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/TagHelpers/ExtendedAnchorTagHelper.cs
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Views/Shared/_CookieBanner.cshtml
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Views/Shared/_Layout.cshtml
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Views/Shared/_Menu.cshtml
SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Views/Shared/_ViewImports.cshtml
SFA.DAS.Provider.Shared.UI/readme.md

Upgrade package to 3.1 from 2.2
Remove dependency on `SFA.DAS.ProviderUrlHelper`
There is now no dependency on StructureMap or AutoConfiguration.
To use, the following configuration element needs to be present:
```
{ 
"ProviderSharedUIConfiguration" :
{
"DashboardUrl":"https://localhost:1234"
}
```
This can exist in your main configuration, as long as it is loaded during startup.
Then in Startup add
```
services.AddProviderUiServiceRegistration(_configuration);
```
Which will add the remaining container registration

AEDB-45 provider shared UI

---

SFA.DAS.Encoding/SFA.DAS.Encoding/EncodingType.cs

Adding an additional "PledgeId" type to the shared encoding project.
See also:
* https://github.com/SkillsFundingAgency/das-apim-endpoints/pull/412
* https://github.com/SkillsFundingAgency/das-employer-config/pull/913

[TM-29] Additional Encoding Type ("PledgeId")

---

SFA.DAS.Encoding/SFA.DAS.Encoding/EncodingType.cs

Adds a new encoding type for pledge application ids.
See also:
* https://github.com/SkillsFundingAgency/das-employer-config/pull/966

[TM-98] View An Application

---

SFA.DAS.Provider.Shared.UI/SFA.DAS.Provider.Shared.UI/Extensions/IdentityExtensions.cs

This covers the scenario where the mapping isnt being done as part of the claims transformation in pirean

FAI-101 - Add fallback claim lookup for ukprn

---

SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/ConfigureDfESignInAuthenticationExtension.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Services/DfESignInService.cs

1) Adding the claims to initial identity rather than creating new identity. 
2) Explicitly define the AuthenticationType as OpenIdConnect otherwise the default will be WSFederation.

Improvements to DfESignInService

---

SFA.DAS.DfESignIn.Auth.Samples/SFA.DAS.DfESignIn.SampleSite/AppStart/AddServiceRegistrationExtension.cs
SFA.DAS.DfESignIn.Auth.Samples/SFA.DAS.DfESignIn.SampleSite/AppStart/CustomServiceRole.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth.UnitTests/AppStart/WhenAddingServicesToTheContainer.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth.UnitTests/Services/DfESignInServiceTest.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/AddAndConfigureDfESignInAuthenticationExtension.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/AddServiceRegistrationExtension.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Interfaces/ICustomServiceRole.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Services/DfESignInService.cs

Introducing CustomServiceRole to instantiate Service Role from client/service application while using DfeSignIn Authentication services.
CustomServiceRoles could be
"http://schemas.microsoft.com/ws/2008/06/identity/claims/role"
"http://schemas.portal.com/service"

Introducing CustomServiceRole to instantiate Service Role from client/service application while using DfeSignIn Authentication services.

---

SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/AddServiceRegistrationExtension.cs

Replace the existing code with newer binding syntax. Previous code wasn't working as expected while trying to bind the configuration with IServiceCollection.
Changes related to Target framework moniker (TFM):  .Net Standard 2.1

Changes to DfESignIn Nuget Package

---

SFA.DAS.DfESignIn.Auth.Samples/SFA.DAS.DfESignIn.SampleSite/AppStart/AddServiceRegistrationExtension.cs
SFA.DAS.DfESignIn.Auth.Samples/SFA.DAS.DfESignIn.SampleSite/Controllers/HomeController.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth.UnitTests/AppStart/WhenAddingServicesToTheContainer.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/AddAndConfigureDfESignInAuthenticationExtension.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/AddServiceRegistrationExtension.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/ConfigureDfESignInAuthenticationExtension.cs

1) Introduced ClientName as a additional paramter under Service Registration. 
2) Ability to hold and read unique Client Configuration settings from from SFA.DAS.Provider.DfeSignIn_1.0 
3) More Unit test to cover the additional code changes
Story Link: https://skillsfundingagency.atlassian.net/browse/FAI-841

FAI-841 Change configuration in DfESignIn package to support multiple client registrations

---

SFA.DAS.DfESignIn.Auth.Samples/SFA.DAS.DfESignIn.SampleSite.Standard/Views/Home/Authenticated.cshtml
SFA.DAS.DfESignIn.Auth.Samples/SFA.DAS.DfESignIn.SampleSite/AppStart/AddServiceRegistrationExtension.cs
SFA.DAS.DfESignIn.Auth.Samples/SFA.DAS.DfESignIn.SampleSite/AppStart/CustomServiceRole.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth.UnitTests/AppStart/WhenAddingCustomServiceRoleTest.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth.UnitTests/AppStart/WhenAddingServicesToTheContainer.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth.UnitTests/Enums/CustomServiceRoleValueTypeTest.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth.UnitTests/Services/DfESignInServiceTest.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/AddAndConfigureDfESignInAuthenticationExtension.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/AddServiceRegistrationExtension.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/ConfigureDfESignInAuthenticationExtension.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Configuration/DfEOidcConfiguration.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Enums/CustomServiceRoleValueType.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Enums/RoleStatus.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Interfaces/ICustomServiceRole.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Services/DfESignInService.cs

1) Added New Property under ICustomServiceRole to define the Role Name or Code while mapping the Claims to the original identity. 
2) SignedOutCallBack Url Property added to Config
3) Other Minor improvements
4) Unit test amendments for the above changes.
#Story: https://skillsfundingagency.atlassian.net/browse/FAI-853

FAI-853 Improvement to DfESignIn Nuget Package and configuration

---

SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth.UnitTests/AppStart/WhenAddingServicesToTheContainer.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth.UnitTests/Services/AuthenticationTicketStoreTests.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/AddServiceRegistrationExtension.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/ConfigureDfESignInAuthenticationExtension.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Configuration/DfEOidcConfiguration.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth.csproj
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Services/AuthenticationTicketStore.cs

Introducing ITicketStore to store the authenticationTicket. 
Store Authentication session in Redis Cache
Story Link: https://skillsfundingagency.atlassian.net/browse/FAI-857

FAI-857 DfESign In - Store Authentication session in Redis

---

SFA.DAS.DfESignIn.Auth.Samples/SFA.DAS.DfESignIn.SampleSite/Controllers/HomeController.cs
SFA.DAS.DfESignIn.Auth.Samples/SFA.DAS.DfESignIn.SampleSite/Program.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Api/Client/DfeSignInApiHelper.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/AddAndConfigureDfESignInAuthenticationExtension.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/ConfigureDfESignInAuthenticationExtension.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/ConfigureDfESignInStubAuthenticationExtension.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/ConfigureSharedAuthenticationExtension.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth.csproj

1) Intercept OpenIdConnect Signout Event with OnSignedOutCallbackRedirect option to destroy the OpenIdConnect Cookie and SignOut the User Auth session 
2) Code Clean-up - in the Services.AddCookie Extension class
Story: https://skillsfundingagency.atlassian.net/browse/FAI-886

FAI-886 Return logged off users to the service start screen

---

SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/AppStart/ConfigureDfESignInAuthenticationExtension.cs
SFA.DAS.DfESignIn.Auth/SFA.DAS.DfESignIn.Auth/Constants/RoutePath.cs

1. Removed Oidc SignOutAsync from Oidc Events as this is handled at Service Application Side.
2. Renamed the Oidc Signout path to "/signout-callback-oidc"
Story: https://skillsfundingagency.atlassian.net/browse/FAI-886

FAI-886 Log off Users from DfE SignIn

---

SFA.DAS.GovUK.Auth/SFA.DAS.GovUK.Auth/SFA.DAS.GovUK.Auth.csproj
SFA.DAS.GovUk.Auth.Samples/SFA.DAS.GovUK.SampleSite/SFA.DAS.GovUK.SampleSite.csproj

Microsoft.Rest.ClientRuntime version is causing build pipelines to fail during package scanning tasks.

Removing Microsoft.Rest.ClientRuntime package 

---

SFA.DAS.Api.Common/SFA.DAS.Api.Common/Infrastructure/AzureClientCredentialHelper.cs
SFA.DAS.Api.Common/SFA.DAS.Api.Common/SFA.DAS.Api.Common.csproj

Issue: APIM trying to get the Bearer token using ManagedIdentity is taking longer than expected. This issue could be happening only in the local/dev box.
Error: The request was cancelled due to the configured HttpClient.Timeout of 100 seconds elapsing. 
Resolution: Setting default timeout for ManagedIdentityCredentials, If it can't get the token using ManagedIdentity try with AzureCLI.

Get Bearer Token set default timeout option for Managed Identity 

---

Configuration/SFA.DAS.Configuration.AzureTableStorage/AzureTableStorageConfigurationProvider.cs
Configuration/SFA.DAS.Configuration.AzureTableStorage/AzureTableStorageConfigurationSource.cs
Configuration/SFA.DAS.Configuration.AzureTableStorage/ConfigurationBuilderExtensions.cs
Configuration/SFA.DAS.Configuration.AzureTableStorage/ConfigurationOptions.cs
Configuration/SFA.DAS.Configuration.AzureTableStorage/StorageOptions.cs
Configuration/SFA.DAS.Configuration.TestHarness/Program.cs
Configuration/SFA.DAS.Configuration.UnitTests/AzureTableStorage/AzureTableStorageConfigurationProviderTests.cs

Change made so that we can have a mix of versions of config defined. This is done by setting the `Options.ConfigurationNameIncludesVersionNumber = true` and then in configuration defining your configuration as `SFA.DAS.MyConfig_1.0,SFA.DAS.MyOtherConfig_2.0`

FAI-2427 - Allow version in config row name

---

SFA.DAS.GovUK.Auth/SFA.DAS.GovUK.Auth.UnitTests/Services/OidcService/WhenGettingToken.cs
SFA.DAS.GovUK.Auth/SFA.DAS.GovUK.Auth/Services/OidcService.cs

We have UsePkce enabled, but due to how we have a custom GetToken implementation this was not being passed with the request. This change now passes the code_verifier parameter with that request

FAI-2465 - Ensure code_verifier is passed with GetToken

---

SFA.DAS.GovUK.Auth/SFA.DAS.GovUK.Auth/SFA.DAS.GovUK.Auth.csproj
SFA.DAS.GovUk.Auth.Samples/SFA.DAS.GovUK.SampleSite/SFA.DAS.GovUK.SampleSite.csproj

Added the following package:
```
<PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.8.0" />
```
so that the incorrect version stops being implicitly referenced and stopping the well-known configuration from being correctly loaded

FAI-2465 Package update
